// SPDX-License-Identifier: ISC
// Copyright (c) 2026 Eric Y. Liu
//! Tauri build script — generates the app context from `tauri.conf.json`, capabilities, and icons,
//! and stages the shell-enhancement plugin tree that `enhancements_io` embeds.

use std::path::{Path, PathBuf};

/// trmx-240 (L14): stage `resources/shell-enhancements` into `OUT_DIR`, WITHOUT any compiled zsh
/// wordcode, and let `include_dir!` embed the staged copy instead of the source tree.
///
/// Filtering at materialization is not enough, and the reason is a compile-time/run-time split that
/// is easy to miss: `include_dir!` bakes the bytes into the binary when the crate is COMPILED, so a
/// runtime filter can stop wordcode reaching a version directory while ~1 MB of it still ships
/// inside the executable. This matters because the real-PTY tests point p10k at the source tree
/// directly, so `cargo test` leaves freshly-compiled `.zwc` there — and CI's macOS job runs the
/// tests BEFORE the packaged build. Staging is the only place that can make "not shipped" true.
fn stage_enhancements() -> PathBuf {
    let src = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../resources/shell-enhancements");
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("shell-enhancements");
    // Rebuild when the vendored tree changes (including a plugin appearing or disappearing).
    println!("cargo:rerun-if-changed={}", src.display());
    let _ = std::fs::remove_dir_all(&out);
    copy_filtered(&src, &out);
    out
}

fn copy_filtered(src: &Path, dst: &Path) {
    std::fs::create_dir_all(dst).unwrap_or_else(|e| panic!("mkdir {}: {e}", dst.display()));
    let entries =
        std::fs::read_dir(src).unwrap_or_else(|e| panic!("read_dir {}: {e}", src.display()));
    for entry in entries.flatten() {
        let from = entry.path();
        let name = entry.file_name();
        if from.is_dir() {
            println!("cargo:rerun-if-changed={}", from.display());
            copy_filtered(&from, &dst.join(name));
        } else if from.extension().is_some_and(|ext| ext == "zwc") {
            // The whole point: compiled wordcode never enters the binary.
            continue;
        } else {
            std::fs::copy(&from, dst.join(name))
                .unwrap_or_else(|e| panic!("copy {}: {e}", from.display()));
        }
    }
}

/// trmx-252 (L13): every command the app registers, declared so the ACL can scope it.
///
/// Without this list Tauri treats app commands as ungoverned — `has_app_manifest()` is false and
/// the capability check is skipped for anything that is not a plugin command, so the settings
/// window can invoke `pty_write` as freely as the terminal can. Declaring it autogenerates an
/// `allow-<kebab-command>` / `deny-<kebab-command>` permission pair per entry (written under
/// `permissions/autogenerated/`, gitignored — regenerated from THIS list on every build), which
/// the capability files then grant per window.
///
/// The list must stay identical to `main.rs`'s `tauri::generate_handler![…]`, and an omission
/// fails CLOSED — the command is denied at runtime, in front of a user, with nothing failing at
/// build time. `tests/command_capabilities.rs` parses both lists and compares them, so the drift
/// surfaces in CI instead.
const COMMANDS: &[&str] = &[
    "core_version",
    "take_pending_open_paths",
    "open_pty",
    "pty_write",
    "pty_ack",
    "pty_resize",
    "close_pty",
    "smoke_config",
    "smoke_done",
    "perf_config",
    "perf_done",
    "config_read",
    "shells_list",
    "effective_shell",
    "config_write",
    "config_reset_all",
    "config_open_file",
    "keys_read",
    "open_settings_window",
    "themes_read",
    "themes_write",
    "themes_open_dir",
    "scripts_list",
    "scripts_open_dir",
    "shell_integration_reveal",
    "control_response",
    "log_message",
    "log_dir",
    "log_open_dir",
    "enhancements_status",
    "quit_confirmed",
    "webview_close_request",
    "close_acknowledged",
];

fn main() {
    let staged = stage_enhancements();
    // Consumed by `enhancements_io`'s include_dir! — see its PLUGINS static.
    println!(
        "cargo:rustc-env=TERMIXION_ENHANCEMENTS_DIR={}",
        staged.display()
    );
    // `try_build`, not `build()`: the app manifest is only reachable through the `Attributes`
    // form. It returns `Result<()>`, and a bare call would leave an unused `Result` — which under
    // `-D warnings` is an error, so the `.expect` is load-bearing rather than decorative.
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("failed to run the Tauri build script");
}
